### ISSUE TITLE
关于实时推理

### ISSUE THREAD

**Issue by kaidachen** [CaA23187/GCCRN_full#1]
请问GCCRN支持流式推理，实时回声消除吗？

**Comment by CaA23187** [comment]
你好, GCCRN是因果/半因果系统，没有用到未来帧的信息（半因果设置只用到了一帧未来帧，整体的延迟可以控制在40ms以内）理论上支持流式推理。如果认为延迟在40ms以内就算实时的话，那可以说支持实时回声消除。

**Comment by kaidachen** [comment]
感谢回答，为了实现实时推理，是否需要修改GCCRN的forward()函数，缓存lstm的state等操作？

关于流式推理脚本您有没有计划开源？

**Comment by CaA23187** [comment]
关于流式推理，我并未编写相关脚本，只是从理论上进行了可行性的分析。可以参考rnnoise的程序进行修改。

此外forward函数里的LSTM是单向的，在实时推理中不需要进行额外的修改。
